import { PageShell } from "@/components/layout/site-shell";
import { DemoNotice } from "@/components/ui/evidence";
import { surveillance } from "@/lib/data";

export const metadata = { title:"AFM Now" };
export default function AfmNow() { const max = Math.max(...surveillance.years.map(d=>d.cases));
 return <PageShell><DemoNotice/><section className="container py-16"><p className="eyebrow">Surveillance</p><h1 className="display mt-3 text-5xl text-[#173a32] md:text-6xl">AFM Now</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#53635d]">The current AFM surveillance picture, with historical context and source transparency.</p><div className="mt-10 grid gap-px overflow-hidden border rule bg-[#d6dcd6] sm:grid-cols-2 lg:grid-cols-4">{surveillance.metrics.map(([label,value,note])=><div key={label} className="bg-white/50 p-5"><p className="text-sm text-[#62716b]">{label}</p><p className="display mt-4 text-4xl">{value}</p><p className="mt-2 text-xs text-[#71807a]">{note}</p></div>)}</div>
 <section className="mt-14 grid gap-12 lg:grid-cols-[1.4fr_.6fr]"><div><h2 className="display text-3xl">Historical reports in context</h2><p className="mt-3 text-sm leading-6 text-[#5d6b65]">Historical values are presented only as an explicitly labeled development fixture. The production source adapter will retain every source snapshot and show its update date.</p><div className="mt-7 flex h-64 items-end gap-2 border-b border-l rule p-4">{surveillance.years.map(row=><div className="group flex h-full flex-1 flex-col justify-end" key={row.year}><div aria-label={`${row.year}: ${row.cases} cases`} className="min-h-1 bg-[#38705f] group-hover:bg-[#c7663e]" style={{height:`${row.cases/max*100}%`}}/><span className="mt-2 -rotate-45 text-[10px] text-[#63726c]">{row.year}</span></div>)}</div><p className="mt-5 text-sm"><a className="font-bold underline underline-offset-4" href={surveillance.sourceUrl} target="_blank">View original CDC source ↗</a></p></div>
 <aside className="card h-fit p-6"><p className="eyebrow">Related viral activity</p><h2 className="display mt-3 text-2xl">Context, not prediction.</h2><p className="mt-4 text-sm leading-6 text-[#55645e]">Related enterovirus activity provides epidemiologic context and should not be interpreted as an individual risk estimate or a direct prediction of AFM cases.</p><div className="mt-6 border-t rule pt-5"><p className="font-bold">What this means</p><p className="mt-2 text-sm leading-6 text-[#5b6863]">No linked research evidence is available until the publication index is ingested.</p></div></aside></section>
 <p className="mt-12 border-t rule pt-5 text-xs text-[#66746e]">Source: {surveillance.source}. Source update: {surveillance.sourceUpdated}. Local ingestion: {new Date(surveillance.ingestedAt).toLocaleString("en-US", {dateStyle:"medium", timeStyle:"short"})} UTC.</p></section></PageShell>; }
