import Link from "next/link";
import { PageShell } from "@/components/layout/site-shell";
import { EvidenceBadge, DemoNotice } from "@/components/ui/evidence";
import { mechanismWatch, openQuestions, publications, surveillance } from "@/lib/data";

const Arrow = () => <span aria-hidden>↗</span>;
export default function Home() {
 return <PageShell><DemoNotice/>
  <section className="container border-b rule py-20 md:py-28"><p className="eyebrow">Scientific intelligence for acute flaccid myelitis</p><h1 className="display mt-5 max-w-4xl text-6xl leading-[.94] text-[#173a32] md:text-8xl">From surveillance<br/>to understanding.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#4c5d57]">Track AFM surveillance, follow new research, explore the laboratories studying it, and see how scientific understanding changes over time.</p><div className="mt-10 flex flex-wrap gap-3"><Link className="focus-ring bg-[#173a32] px-5 py-3 text-sm font-bold text-white hover:bg-[#285348]" href="/afm-now">Explore AFM Now <Arrow/></Link><Link className="focus-ring border border-[#173a32] px-5 py-3 text-sm font-bold hover:bg-[#e7eee9]" href="/research">Open Research Radar <Arrow/></Link></div></section>
  <section className="container py-16"><div className="flex items-end justify-between"><div><p className="eyebrow">AFM Now</p><h2 className="display mt-2 text-4xl text-[#173a32]">Surveillance, with context.</h2></div><Link className="text-sm underline underline-offset-4" href="/afm-now">Explore surveillance <Arrow/></Link></div><div className="mt-8 grid gap-px overflow-hidden rounded border rule bg-[#d6dcd6] sm:grid-cols-2 lg:grid-cols-4">{surveillance.metrics.map(([label,value,note])=><div key={label} className="bg-[#f7f6f1] p-5"><p className="text-sm text-[#60706b]">{label}</p><p className="display mt-4 text-4xl text-[#173a32]">{value}</p><p className="mt-3 text-xs text-[#7a827e]">{note}</p></div>)}</div></section>
  <section className="border-y rule bg-[#e9eee8] py-16"><div className="container"><p className="eyebrow">Research pulse</p><h2 className="display mt-2 text-4xl text-[#173a32]">The index is ready for evidence.</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{["New relevant publications","Researchers publishing recently","Institutions with recent activity","New mechanism evidence"].map(label=><div className="card p-5" key={label}><p className="text-sm text-[#53625d]">{label}</p><p className="display mt-6 text-3xl">—</p><p className="mt-3 text-xs text-[#6a7772]">Available after source ingestion</p></div>)}</div></div></section>
  <section className="container grid gap-8 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Global research activity</p><h2 className="display mt-2 text-4xl text-[#173a32]">A map built from public records.</h2><div className="mt-7 grid min-h-72 place-items-center border border-[#d6dcd6] bg-[#dfe9e3] text-center"><div><p className="text-sm text-[#52615b]">Institution geography appears after OpenAlex enrichment.</p><Link className="mt-4 inline-block text-sm font-bold underline underline-offset-4" href="/map">Explore research map <Arrow/></Link></div></div></div><div className="border-l-0 lg:border-l lg:pl-8 rule"><p className="eyebrow">Mechanism watch</p><h2 className="display mt-2 text-4xl text-[#173a32]">Knowledge with its edges visible.</h2><div className="mt-7 space-y-3">{mechanismWatch.map(item=><div className="card p-4" key={item.name}><div className="flex justify-between gap-3"><strong>{item.name}</strong><EvidenceBadge status={item.status}/></div><p className="mt-2 text-sm leading-6 text-[#5a6963]">{item.note}</p></div>)}</div><Link className="mt-6 inline-block text-sm font-bold underline underline-offset-4" href="/mechanism">Explore mechanism <Arrow/></Link></div></section>
  <section className="container border-t rule py-16"><div className="grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Latest research</p><h2 className="display mt-2 text-4xl text-[#173a32]">Evidence, never implied.</h2><article className="card mt-7 p-5"><p className="eyebrow">{publications[0].category}</p><h3 className="display mt-4 text-2xl">{publications[0].title}</h3><p className="mt-3 text-sm text-[#5a6963]">No papers are displayed as current until imported from their original source.</p><Link className="mt-4 inline-block text-sm font-bold underline underline-offset-4" href={`/publications/${publications[0].id}`}>View record <Arrow/></Link></article></div><div><p className="eyebrow">What scientists still don&apos;t know</p><h2 className="display mt-2 text-4xl text-[#173a32]">Open questions deserve equal prominence.</h2><ol className="mt-7 space-y-4">{openQuestions.map((question,i)=><li className="border-t rule pt-4 text-lg leading-7" key={question}><span className="mr-3 text-sm text-[#71807a]">0{i+1}</span>{question}</li>)}</ol></div></div></section>
 </PageShell>;
}
